name: Hello World Actions
on: [push]
jobs:
  hello-world-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!!!!"
      - run: echo "Ando probando Actions XD"
      - run: echo "Siuuuuu 🚀"
      - name: Crea uno archivos
        run: touch file1.txt
      - name: guarda el listado de archivos
        run: ls -al > file2.txt
      - run: echo "Agrego una línea a file2.txt" >> file2.txt
      - run: cat file2.txt
      - run: ls -al